### ISSUE TITLE
Latest / oldest sorting not working properly on proposals search

### ISSUE THREAD

**Issue by andyesp** [decentraland/governance#1354]
Reproduction steps:
* Go to https://governance.decentraland.org
* Search "0x511a22cDd2c4eE8357bB02df2578037Ffe8a4d8d"
* Check proposals

![Image](https://github.com/decentraland/governance/assets/8242162/cdff1675-d5ba-4727-8f2c-8b8c5e3c65f5)

**Comment by ginocingolani** [comment]
Search uses a relevance-based approach to sort (Using keywords), that's why Latest/Oldest feels weird.
The solution should be:
* Adding a sorting option called "Relevance", make it the default option. Follows the current logic.
* Latest & Oldest should sort results based only publication timestamp
This only applies to the sorting options when using Search. Proposal list maintain the Oldest/Latest approach.
