### ISSUE TITLE
Add Get VP button to the profile view

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1499]
Description: https://www.loom.com/share/342b05fbbd194ea9b8c9f38775a2914c?sid=f250547c-5e18-4e5c-a819-bfd62aa35731

Links

LAND: https://decentraland.org/marketplace/lands?assetType=nft&section=land&vendor=decentraland&page=1&sortBy=newest&onlyOnSale=true
L1 Wearables: https://decentraland.org/marketplace/browse?assetType=item&section=wearables&vendor=decentraland&page=1&sortBy=newest&status=on_sale&network=ETHEREUM
NAME: https://decentraland.org/builder/claim-name
MANA: https://decentraland.org/account/

**Comment by heyimjuani** [comment]
Showing guides for reference.
- Question: should this CTA only be displayed on a given user's own profile?
- "Get more VP" CTA is aligned to the right. Clicking on it toggles a dropdown
- Avatar is to be centered vertically considering the vertical space used by the 3 rows of content on its left. Changing avatar size or canvas may be needed
- for mobile, in order to save space, CTA is smaller and loses the word "more" + the dropdown arrow. Username may have to be escaped/limited for the button to fit.

https://www.figma.com/file/e0IFJjplUdYdQJ2NtLwvMf/DAO-v2-(Guane)?type=design&node-id=6884-3024&mode=dev
![Image](https://github.com/decentraland/governance/assets/467712/a756072a-9999-4a65-b278-b0722fbe23fc)

![Image](https://github.com/decentraland/governance/assets/467712/d1308b20-e5f1-4162-97e3-00d51a2ad003)

![Image](https://github.com/decentraland/governance/assets/467712/952d08d4-1e93-40e6-8ad6-df4fedc07b41)
