### ISSUE TITLE
Are votes being counted correctly?

### ISSUE THREAD

**Issue by eordano** [decentraland/governance#628]
This calculation, "2.5M needed for acceptance", completely confuses me. Would this mean that even if the proposal has 11M VP against it, reaching 8M is enough to make a vote pass? 

![image](https://user-images.githubusercontent.com/42750/207660105-6bd3d9b7-ad48-4448-b06e-744680d1faa2.png)

**Comment by ginocingolani** [comment]
@eordano Votes are being counted correctly, what probably is confusing you is the term _acceptance_.

For a proposal to be considered approved/passed two conditions are needed:
1. The YES option must reach the VP Threshold required for the category (In this case 8M VP for a 240k grant)
2. A simple majority of participating VP must vote for the YES

In this case, the proposal would not pass since it doesn't get the minimum VP required and the NO is higher than the YES.
